AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Reproducing the aws lambda webapp reference architecture - a todo app
  - but with java.
Resources:
  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: todo-table
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
  getAllTodos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://acg-devops-joseph/8d60f8ad0e158952d1962656f20c086b
      Handler: todo.getall.GetAllTodosHandler
      Runtime: java11
      Description: Java function
      FunctionName: todo-getall
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  createTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://acg-devops-joseph/8d60f8ad0e158952d1962656f20c086b
      Handler: todo.create.CreateTodoHandler
      Runtime: java11
      Description: Java function
      FunctionName: todo-create
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TodoTable
      Tracing: Active
  deleteTodo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://acg-devops-joseph/8d60f8ad0e158952d1962656f20c086b
      Handler: todo.delete.DeleteTodoHandler
      Runtime: java11
      Description: Java function
      FunctionName: todo-delete
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      - DynamoDBCrudPolicy:
          TableName:
            Ref: TodoTable
      Tracing: Active
