AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Reproducing the aws lambda webapp reference architecture - a todo app
  - but with java.
Resources:
  TodoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: todo-table
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
  getAllTodos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://acg-devops-joseph/5f6a0a8db246fd16dd15cb7a7d3f9147
      Handler: todo.getall.GetAllTodosHandler
      Runtime: java11
      Description: Java function
      FunctionName: todo-getall
      MemorySize: 512
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
