AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Reproducing the aws lambda webapp reference architecture - a todo app - but with java.
Resources:
  getAllTodos:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/webapp-refarch-todo-java-0.0.1-SNAPSHOT.jar
      Handler: todo.getall.GetAllTodosHandler
      Runtime: java11
      Description: Java function
      FunctionName: todo-getall
      MemorySize: 128
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
